version: "3.8"

services:
  socks7:
    build: .
    container_name: socks7-v2rei
    ports:
      - "1080:1080"
    environment:
      # Leave empty to auto-generate random username & password
      - SOCKS7_USERNAME=
      - SOCKS7_PASSWORD=
      - RUST_LOG=info
    restart: unless-stopped
