name: Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            name: socks7-linux-x64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            name: socks7-windows-x64.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            name: socks7-macos-x64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --release
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: |
            target/release/socks7
            target/release/socks7.exe
